### ISSUE TITLE
Support for schema dereferencing before validation.

### ISSUE THREAD

**Issue by georgeslabreche** [frictionlessdata/datapackage-java#14]
Support for schema dereferencing before validation:

- [x] resource.schema
- [x] resource.dialect

**Comment by georgeslabreche** [comment]
@roll: I read the section _"on dereferencing and descriptor validation"_ in [these specs](https://frictionlessdata.io/specs/implementation/) as well as the GitHub Issue on ["Dereference pointers before descriptor validation."](https://github.com/frictionlessdata/specs/issues/365) and [this javascript implementation](https://github.com/frictionlessdata/datapackage-js/blob/master/src/helpers.js#L69-L79). However, I'm not sure I'm fully grasping what needs to be done. Sounds simple but I think I'm missing something.

**Comment by roll** [comment]
@georgeslabreche 
Consider a resource descriptor:

```yml
name: name
schema: http://example.com/schema.json
profile: tabular-data-resource
```

Now if you validate it against JSON Schema profile (http://specs.frictionlessdata.io/schemes/tabular-data-resource.json) in reality almost no checks will be done.

So first we need to load http://example.com/schema.json:

```yml
name: name
schema: {fields: [...]} # could be a lot of validation errors 
profile: tabular-data-resource
```

And only then to do a validation.
